### ISSUE TITLE
RAT

### ISSUE THREAD

**Issue by VMpc** [efenatuyo/ugc-sniper#29]
#28

**Comment by efenatuyo** [comment]
guys he is saying that checking a database is a rat

**Comment by VMpc** [comment]
you literally call an unsolicited http request (which calls another to a private pastebin) :trollface:

**Comment by efenatuyo** [comment]
that is lit for executing the WEBSITE. You still see what you GIVE in your requests. are you actually stupid? You are saying the most random shit.

**Comment by VMpc** [comment]
you are ratting people stop your lying, you are a script kiddie

**Comment by efenatuyo** [comment]
okay now explain me how it is ratting

**Comment by efenatuyo** [comment]
so let me say this.

sending a request to a webserver can grab your personal information. So you are saying if I go on a random website there is a chance that it can get my passwords and more?
