### ISSUE TITLE
Wdym aiohttp dosent support proxies?

### ISSUE THREAD

**Issue by Zaid000000** [efenatuyo/ugc-sniper#6]
# Idk what i did but this definitly works if you put it in a directory with a notepad file called "proxylist" 
# I have zero knowledge of python so if misunderstood and this still wont work with the remaining code then am sorry i only know LUA, #this did work tho and it printed out the working proxies i just dont know how to implement it in your code 

import datetime
import json
import os
import uuid
import asyncio
import random
import requests
import configparser
from colorama import Fore, Back, Style
import aiohttp

config = configparser.ConfigParser()
config.read('config.ini')

class Sniper:
    def __init__(self) -> None:
        self.webhookEnabled = False if not "configWebhook" in config or not bool(config["configWebhook"]["enabled"] == "on") else True
        self.webhookUrl = config["configWebhook"]["webhook"] if self.webhookEnabled else None
        self.accounts = None
        self.items = self._load_items()
        self.title = (""" PROXY CHECKER  - ZAID""")
        self.checks = 0
        self.buys = 0
        self.request_method = 2
        self.total_ratelimits = 0
        self.last_time = 0
        self.errors = 0
        self.clear = "cls" if os.name == 'nt' else "clear"
        self.version = "6.0.0"
        self.task = None
        self.scraped_ids = []
        self.latest_free_item = {}
        self._setup_accounts()

    def _load_items(self):
        pass

    def _setup_accounts(self):
        pass

    async def start(self):
        pass

    async def check_version(self):
        pass

    def _print_stats(self):
        pass

    async def check(self, proxy):
       async with aiohttp.ClientSession() as session:
        try:
            async with session.get('http://httpbin.org/ip', proxy=f'http://{proxy}', timeout=aiohttp.ClientTimeout(total=2), ssl = False) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    self.workingProxies.append(proxy)
                    print(f"Proxy {proxy} is working. IP: {data['origin']}")
                    return
        except aiohttp.client_exceptions.ServerDisconnectedError:
            print(f"Server disconnected while checking proxy {proxy}. Moving on to next proxy.")
            return
        except aiohttp.client_exceptions.ClientOSError:
            print(f"Server disconnected while checking proxy {proxy}. Moving on to next proxy.")
            return
        except aiohttp.client_exceptions.TooManyRedirects:
            print(f"Server disconnected while checking proxy {proxy}. Moving on to next proxy.")
            return
        except asyncio.TimeoutError:
            print(f"Timeout while checking proxy {proxy}. Moving on to next proxy.")
            return

    def get_working_proxy(self):
        if len(self.workingProxies) != 0:
            proxy = random.choice(self.workingProxies)
            return f"http://{proxy}"
        else:
            return None

    async def start_proxy(self):
        self.status = "Proxy checker"
        self._print_stats()
        coroutines = []
        for proxy in self.proxylist:
            coroutines.append(self.check(proxy))
        await asyncio.gather(*coroutines)

s = Sniper()
s.proxylist = open("proxylist.txt").read().splitlines()
s.workingProxies = []
asyncio.run(s.start_proxy())
print(s.workingProxies)

#proof I guess?
https://user-images.githubusercontent.com/130939501/232350368-76241fd1-2274-4cfc-a9b8-76364042523a.mp4

**Comment by efenatuyo** [comment]
Aiohttp supports Proxies but it makes it much slower. Also on nearly every windows device you can‘t use Proxies because windows doesn’t send requests with Proxies and just gets you ssl or timeout errors

**Comment by efenatuyo** [comment]
Conclusion aiohttp wont work on windows or will make it slower using it
